[functions]
  node_bundler = "esbuild"

# (optional) You can skip these headers since we set CORS in the function too.
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "POST, OPTIONS"
